### ISSUE TITLE
Handling Discourse Comments

### ISSUE THREAD

**Issue by michiecat** [a8cteam51/calculated-risk#1]
Comments are powered by Discourse. The comment link on each post leads to a thread on http://hoocoodanode.org/. Discourse has a plugin for WordPress that's similar to the Blogger integration: 

Ken Cooper, who helps Bill run the Discourse setup, had sent in some suggestions for making this plugin work with WordPress (using the Discourse API): https://github.com/discourse/wp-discourse

1) Required options for HCN under Discourse Settings:

Discourse URL: "http://hoocoodanode.org"
API Key: <private>
Publishing username: “CalculatedRisk" (note no space)
Published category: “Blog Post” (note space)
Auto Publish: checked
Use Discourse Comments: checked

2) Put this at the bottom of function.php of the theme. It’s the template that generates the body of a topic on HCN.

```
function discourse_publish_format( $input ) {
    ob_start();
    ?>

    Original post may be found on <a href='{blogurl}'>Calculated Risk</a>.

    <?php
    $output = ob_get_clean();
    return $output;
}
add_filter( 'discourse_publish_format_html', 'discourse_publish_format' );
```

**Comment by sarahmonster** [comment]
I've set this up according to the instructions above, but it may require further configuration in order to work correctly.

**Comment by michiecat** [comment]
Closing because Bill says he does not plan to carry the comments over.
